###Add to a new User
POST http://localhost:3000/api/user/add
Content-Type: application/json

{
    "Nombre": "dagmar",
    "CorreoElectronico": "dagmarzolani@gmail.com",
    "Contraseña": "juntosporsimpre"
}


### list to User
GET http://localhost:3000/api/user/list
Content-Type: application/json



### Listar un solo usuario
GET http://localhost:3000/api/user/query?_id=60132fc3de0cd406d078692d
Content-Type: application/json


###update to user
PUT http://localhost:3000/api/user/update
Content-Type: application/json

{
    "Nombre": "hjola",
    "CorreoElectronico": "dasf",
    "Contraseña": "345456",
    "_id":"601332442bfff72b78ebbe92"
}